# Generated by Django 6.0.6 on 2026-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='final_score',
            field=models.IntegerField(default=0),
        ),
    ]
