# Generated by Django 6.0.6 on 2026-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
    ]
