# Generated by Django 6.0.6 on 2026-06-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_candidate_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
    ]
