# Generated by Django 6.0.6 on 2026-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
